{
 "title": "OHGO Sensor Data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Temperature *F",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ohgo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"airTemperature\" or r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"airTemperature\", \"latitude\", \"longitude\"])"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ohgo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"humidity\", \"latitude\", \"longitude\"])"
    }
   ]
  },
  {
   "title": "Precipitation Rate",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"ohgo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precipitationRate\" or r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"precipitationRate\", \"latitude\", \"longitude\"])"
    }
   ]
  },
  {
   "title": "Average Wind Speed",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"ohgo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"averageWindSpeed\" or r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"averageWindSpeed\", \"latitude\", \"longitude\"])"
    }
   ]
  },
  {
   "title": "Max Wind Speed",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"ohgo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"maximumWindSpeed\" or r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"maximumWindSpeed\", \"latitude\", \"longitude\"])"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 7, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"ohgo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"windDirection\" or r[\"_field\"] == \"averageWindSpeed\" or r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"windDirection\", \"averageWindSpeed\", \"latitude\", \"longitude\"])"
    }
   ]
  }
 ]
}